import type { Dish } from '@/types/orders';

export function buildInitialDishes(): Dish[] {
  return [
  {
    id: 'dish-hamburguesa',
    name: 'Hamburguesa clásica',
    categoryId: 'cat-principales',
    price: 3500,
    recipe: [
      { ingredientId: 'ing-pan-hamburguesa', ingredientName: 'Pan de hamburguesa', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-carne-picada', ingredientName: 'Carne picada', quantity: 0.2, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-queso-cheddar', ingredientName: 'Queso cheddar', quantity: 0.05, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-lechuga', ingredientName: 'Lechuga', quantity: 0.25, unit: 'unidades', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-tomate', ingredientName: 'Tomate', quantity: 0.1, unit: 'kg', isOptional: true, canBeRemoved: true },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Hamburguesa de carne con queso, lechuga y tomate',
  },
  {
    id: 'dish-milanesa-napolitana',
    name: 'Milanesa napolitana',
    categoryId: 'cat-principales',
    price: 4200,
    recipe: [
      { ingredientId: 'ing-nalga', ingredientName: 'Nalga', quantity: 0.3, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-huevos', ingredientName: 'Huevos', quantity: 2, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-pan-rallado', ingredientName: 'Pan rallado', quantity: 0.1, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-pure-tomate', ingredientName: 'Puré de tomate', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-queso-mozzarella', ingredientName: 'Queso mozzarella', quantity: 0.1, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-oregano', ingredientName: 'Orégano', quantity: 0.01, unit: 'kg', isOptional: true, canBeRemoved: true },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Milanesa napolitana con jamón, queso y salsa de tomate',
  },
  {
    id: 'dish-ensalada-mixta',
    name: 'Ensalada mixta',
    categoryId: 'cat-entradas',
    price: 1800,
    recipe: [
      { ingredientId: 'ing-lechuga', ingredientName: 'Lechuga', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-tomate', ingredientName: 'Tomate', quantity: 0.2, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-cebolla', ingredientName: 'Cebolla', quantity: 0.1, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-aceite-oliva', ingredientName: 'Aceite de oliva', quantity: 0.05, unit: 'litros', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-vinagre', ingredientName: 'Vinagre', quantity: 0.02, unit: 'litros', isOptional: true, canBeRemoved: true },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Ensalada fresca con lechuga, tomate, cebolla y aderezo',
  },
  {
    id: 'dish-omelette-jamon-queso',
    name: 'Omelette de jamón y queso',
    categoryId: 'cat-entradas',
    price: 2200,
    recipe: [
      { ingredientId: 'ing-huevos', ingredientName: 'Huevos', quantity: 3, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-jamon-cocido', ingredientName: 'Jamón cocido', quantity: 0.1, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-queso-cremoso', ingredientName: 'Queso cremoso', quantity: 0.1, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-manteca', ingredientName: 'Manteca', quantity: 0.02, unit: 'kg', isOptional: false, canBeRemoved: false },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Omelette relleno de jamón cocido y queso cremoso',
  },
  {
    id: 'dish-pizza-mozzarella',
    name: 'Pizza mozzarella',
    categoryId: 'cat-principales',
    price: 3800,
    recipe: [
      { ingredientId: 'ing-harina-000', ingredientName: 'Harina 000', quantity: 0.5, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-levadura', ingredientName: 'Levadura', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-aceite-girasol', ingredientName: 'Aceite de girasol', quantity: 0.1, unit: 'litros', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-tomate-triturado', ingredientName: 'Tomate triturado', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-queso-mozzarella', ingredientName: 'Queso mozzarella', quantity: 0.3, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-oregano', ingredientName: 'Orégano', quantity: 0.01, unit: 'kg', isOptional: true, canBeRemoved: true },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Pizza de mozzarella clásica con salsa de tomate',
  },
  {
    id: 'dish-papas-fritas',
    name: 'Papas fritas',
    categoryId: 'cat-guarniciones',
    price: 1500,
    recipe: [
      { ingredientId: 'ing-papa', ingredientName: 'Papa', quantity: 0.4, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-aceite-girasol', ingredientName: 'Aceite de girasol', quantity: 0.2, unit: 'litros', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-sal', ingredientName: 'Sal', quantity: 0.01, unit: 'kg', isOptional: false, canBeRemoved: false },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Papas fritas crujientes',
  },
  {
    id: 'dish-pancho-completo',
    name: 'Pancho completo',
    categoryId: 'cat-principales',
    price: 2800,
    recipe: [
      { ingredientId: 'ing-pan-pancho', ingredientName: 'Pan de pancho', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-salchichas', ingredientName: 'Salchichas', quantity: 1, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-salsa-golf', ingredientName: 'Salsa golf', quantity: 0.05, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-mostaza', ingredientName: 'Mostaza', quantity: 0.03, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-choclo-lata', ingredientName: 'Choclo en lata', quantity: 0.5, unit: 'unidades', isOptional: true, canBeRemoved: true },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Pancho completo con salsa golf, mostaza y choclo',
  },
  {
    id: 'dish-tarta-verduras',
    name: 'Tarta de verduras',
    categoryId: 'cat-principales',
    price: 3200,
    recipe: [
      { ingredientId: 'ing-tapas-empanadas', ingredientName: 'Tapas para empanadas', quantity: 2, unit: 'unidades', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-cebolla', ingredientName: 'Cebolla', quantity: 0.2, unit: 'kg', isOptional: false, canBeRemoved: false },
      { ingredientId: 'ing-zapallito', ingredientName: 'Zapallito', quantity: 2, unit: 'unidades', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-morron-rojo', ingredientName: 'Morrón rojo', quantity: 1, unit: 'unidades', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-queso-cremoso', ingredientName: 'Queso cremoso', quantity: 0.2, unit: 'kg', isOptional: true, canBeRemoved: true },
      { ingredientId: 'ing-huevos', ingredientName: 'Huevos', quantity: 2, unit: 'unidades', isOptional: false, canBeRemoved: false },
    ],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Tarta de verduras con cebolla, zapallito y morrón',
  },
  ];
}
